### ISSUE TITLE
New `ssh-add -l` format

### ISSUE THREAD

**Issue by mathstuf** [funtoo/keychain#24]
Looks like `ssh-add -l` (as of openssh-clients-6.7p1-2.fc22.x86_64 at least) has a new (unrecognized) output format:

```
2048 SHA256:XXXXX .../AAA (RSA)
2048 SHA256:XXXXX .../BBB (RSA)
2048 SHA256:XXXXX .../CCC (RSA)
4096 SHA256:XXXXX .../DDD (RSA)
4096 SHA256:XXXXX .../EEE (RSA)
```

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2114

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
