### ISSUE TITLE
Not work in ubuntu 14.04

### ISSUE THREAD

**Issue by horsley** [funtoo/keychain#28]
It seems that the agent is started but didn't add any keys

```
horsleyli@horsleyli-asus:~$ cat ~/.bash_profile 
#!/bin/sh
/usr/bin/keychain $HOME/.ssh/id_rsa
source $HOME/.keychain/$HOSTNAME-sh

horsleyli@horsleyli-asus:~$ ll ~/.ssh
total 28
drwx------  2 horsleyli horsleyli  4096 12月 11 00:29 ./
drwxr-xr-x 61 horsleyli horsleyli  4096  2月 24 01:35 ../
-rw-------  1 horsleyli horsleyli  1743  1月 22  2014 id_rsa
-rw-------  1 horsleyli horsleyli   483  7月 27  2013 id_rsa.pub
-rw-r--r--  1 horsleyli horsleyli 11052  2月 15 13:23 known_hosts
horsleyli@horsleyli-asus:~$ ssh-add -l
The agent has no identities.
horsleyli@horsleyli-asus:~$
```

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2126

**Comment by danielrobbins** [comment]
Try sourcing your bash-profile:

$ source ~/.bash_profile

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
