### ISSUE TITLE
support `keychain -l`

### ISSUE THREAD

**Issue by gnowxilef** [funtoo/keychain#29]
`keychain -l` should behave in the same way that `ssh-add -l` does.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2164

**Comment by danielrobbins** [comment]
Can you provide more detail on this?

**Comment by gnowxilef** [comment]
`keychain -l` should list the ssh keys that are in your agent just like how `ssh-add -l` does.

**Comment by danielrobbins** [comment]
I've added this feature to the repo :)

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
