### ISSUE TITLE
Support for latest `ssh-keygen -l -f foo` output

### ISSUE THREAD

**Issue by clacke** [funtoo/keychain#34]
I just updated openssh on my cygwin and `ssh-keygen` has a new form of output:

    $ ssh-keygen -l -f ~/.ssh/id_rsa
    4096 SHA256:n2CLvs7hleghcyPIf/oyNVQKCuOxMXctIzKlLga3vL4 user@machine (RSA)

This makes keychain output this when I open a new terminal:

     * Warning: Can't determine fingerprint from the following line, falling back to filename

**Comment by clacke** [comment]
$ ssh -V
    OpenSSH_6.8p1, OpenSSL 1.0.2a 19 Mar 2015

**Comment by clacke** [comment]
See http://www.openssh.com/txt/release-6.8:

 * Add FingerprintHash option to ssh(1) and sshd(8), and equivalent
   command-line flags to the other tools to control algorithm used
   for key fingerprints. The default changes from MD5 to SHA256 and
   format from hex to base64.

   Fingerprints now have the hash algorithm prepended. An example of
   the new format: SHA256:mVPwvezndPv/ARoIadVY98vAC0g+P/5633yTC4d/wXE
   Please note that visual host keys will also be different.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2234

**Comment by danielrobbins** [comment]
Okay, and have you tried updating *keychain*? 2.8.0 has support for this.

**Comment by clacke** [comment]
Cool, then I'll just wait until it trickles into cygwin. Thanks!

**Comment by clacke** [comment]
(or just overwrite my /usr/bin/keychain with https://raw.githubusercontent.com/funtoo/keychain/master/keychain.sh , of course)
