### ISSUE TITLE
--confhost does not work on OSX

### ISSUE THREAD

**Issue by grimm26** [funtoo/keychain#36]
I'm running OSX 10.9.5

```
% keychain --agents ssh --inherit any --confhost

 * keychain 2.8.0 ~ http://www.funtoo.org
 * Inheriting ssh-agent (36488)
/opt/local/bin/keychain: line 1155: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/opt/local/bin/keychain: line 1165: *.somewhere.com: syntax error: operand expected (error token is "*.somewhere.com")
```
darwin only has bash 3 and `declare` does not seem to support `-A`. Even when I install bash4 with port I still get:
```
/opt/local/bin/keychain: line 1165: keypaths["$h"]: bad array subscript
```

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2343

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
