### ISSUE TITLE
Don't override $PATH

### ISSUE THREAD

**Issue by jbergstroem** [funtoo/keychain#40]
On OS X using homebrew, keychain is pretty unusable if you want to use openssh or gnupg/gnupg2 from homebrew since [keychain overrides path](https://github.com/funtoo/keychain/blob/master/keychain.sh#L17) and hombrew installs everything into `/usr/local/bin`. 

I'd suggest not setting/overriding it at all.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2465

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
