### ISSUE TITLE
Scp issue when distant keychain not loaded

### ISSUE THREAD

**Issue by isador999** [funtoo/keychain#43]
I don't know if it's a bug, or an improvement idea : 

When I use SCP to another server, which has not already load the key, the prompt is blocked, key isn't asked ... 
But using SSH, key is correctly asked. 

Of course, for SCP, the workaround is '--noask' option.   
But I need to be prompted when I launch SSH (and not SCP.. )  

Maybe it could be a way to do that ?   Detect when prompting if SCP or SSH has been entered ?

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2615

**Comment by danielrobbins** [comment]
Adding your keys ahead of time will allow ssh and scp to happen without entering a passphrase.
