### ISSUE TITLE
[Request] Option not to enter pass-phrase on start

### ISSUE THREAD

**Issue by funkycode** [funtoo/keychain#48]
It would be nice to have an option not to enter manually pass-phrase on start but request it on first usage instead.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2751

**Comment by danielrobbins** [comment]
I am not sure if this is technically feasible, as I think it would require improvements to ssh-agent and ssh-add itself. Do you know of a way to do this?

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.

**Comment by simonvanderveldt** [comment]
@danielrobbins one option would be to work in a similar way as https://github.com/ccontavalli/ssh-ident works, which basically replaces `ssh` by either adding it first on your path or setting an alias. So when `ssh` is invoked it actually executes `ssh-ident` which then exec's `ssh` again. This would allow keychain to do it's thing only when ssh is actually used.

I'm not sure how bug-prone that approach is though. `hub`, github's command line tool, suggests to alias `git` to `hub` and I had some issues with tab-completion after doing that.

I'd really like this functionality as well, thought it made sense to add a comment to this existing issues.
