### ISSUE TITLE
The timeout option does not seem to apply go gpg-agent. 

### ISSUE THREAD

**Issue by drufat** [funtoo/keychain#50]
It only applies to ssh-agent. Is there a way to make it also apply to the gpg keys that are loaded into memory?

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2862

**Comment by danielrobbins** [comment]
I don't think there is a gpg option for this, so closing. Open to pull requests if I am wrong.
