### ISSUE TITLE
Doesn't work under Mac OS X 'El Capitan'

### ISSUE THREAD

**Issue by piccobit** [funtoo/keychain#52]
After updating my MacBook to 'El Capitan' keychain stopped working.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2881

**Comment by danielrobbins** [comment]
Going to need more detail than this. What stopped working? What happens? What command are you running?

**Comment by piccobit** [comment]
The keychain binary seems to have been disappeared after the update to 'El Capitan', therefore I tried to reinstall keychain again and during that installation I got an error message that this software is not compatible with this OS version. I marked the checkbox to try it nonetheless, but the installation gets aborted soon by the OS.

**Comment by danielrobbins** [comment]
This sounds like you are using an installer of some kind. You should try installing it manually.

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
