### ISSUE TITLE
`keychain -l` fails in Debian

### ISSUE THREAD

**Issue by lucasvc** [funtoo/keychain#53]
In a Debian Jessie, I've installed `keychain=2.8.1-0.1` ([from `stretch` repo](https://packages.debian.org/stretch/all/keychain/download)), as I wanted the listing keys feature. If I didn't imported any key, I get:

    $ keychain -l
    /usr/bin/keychain: 1537: [: end: unexpected operator
    end

Cloning this repo (tag 2.8.1) and executing the `keychain.sh` directly, says the same but line `1375`.
If having more than one, prints the ¿fingerprint? and says something similar.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2956

**Comment by danielrobbins** [comment]
Can you see if the master version from the github repo also exhibits this behavior?

**Comment by lucasvc** [comment]
No, it works as expected using the `keychain` generated from `make` command.
[Created a `Dockerfile` which I used to test](https://gist.github.com/lucasvc/cb58418b4f59ac923ee1#file-dockerfile).
A part of `make`'d from `master`, installed the published 2.8.1-0.1.

**Comment by danielrobbins** [comment]
Okay, in that case I believe that this bug has been fixed and should be resolved in the upcoming 2.8.2 release.
