### ISSUE TITLE
with gpg v2.1 and above GPG_AGENT_INFO is removed

### ISSUE THREAD

**Issue by Lompik** [funtoo/keychain#59]
See https://www.gnupg.org/faq/whats-new-in-2.1.html#autostart for details.
I'm running gpg v2.1 and keychain is able to start the gpg agent. 

However `pidf` files for `gpg` are empty in `~/.keychain`. This lead to this warning `Warning: GPG_AGENT_INFO in environment is invalid; ignoring it` everytime keychain checks for the agent. 
Also `--write-env-file` has no effect in this gpg version.

Regards

**Comment by gretel** [comment]
same same here.

**Comment by reubano** [comment]
Just add this before calling `keychain`: 

```bash
export GPG_AGENT_INFO=`pgrep gpg-agent`.
```

**Comment by tarsius** [comment]
Friendly ping.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/<tornado.concurrent.Future object at 0x7ff655fcfc50>

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/<tornado.concurrent.Future object at 0x7f806de9a940>

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/<tornado.concurrent.Future object at 0x7f5eb115ccf8>

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3405

**Comment by ddoherty03** [comment]
Thanks to @reubano for the hint that got me to a working keychain again.  I use the fish shell, so the syntax is a bit different.  Also, I did the patching up of the GPG_AGENT_INFO *after* running keychain so it picks up agents started by keychain.  Also, I wrote the info to the ~/.keychain files so that keychain recognizes the agents as ones launched by keychain so it does not stop them.  Here is my current config:

```fish
if status --is-interactive
  set -x GPG_AGENT_INFO
  set -x GPG_TTY (tty)
  set -x PINENTRY_USER_DATA "USE_CURSES=1"
  echo "UPDATESTARTUPTTY" | gpg-connect-agent >/dev/null 2>&1
  keychain --eval --noinherit --stop others --agents ssh,gpg id_rsa 7BBA874D C0A9F2F0 | source
  set gpg_info "~/.gnupg/S.gpg-agent:"(pidof gpg-agent)":1"
  set sh_gpg_cmd "GPG_AGENT_INFO="$gpg_info"; export GPG_AGENT_INFO"
  set fish_gpg_cmd "set -x GPG_AGENT_INFO "$gpg_info
  set gpg_sh_file $HOME"/.keychain/"(hostname)"-sh-gpg"
  set gpg_fish_file $HOME"/.keychain/"(hostname)"-fish-gpg"
  set -x GPG_AGENT_INFO $gpg_info
  echo $sh_gpg_cmd >$gpg_sh_file
  echo $fish_gpg_cmd >$gpg_fish_file
end
```

**Comment by reubano** [comment]
@ddoherty03 np! Here's mine

`.bashrc`
```bash
LIFE=28800
export GPG_AGENT_INFO="~/.gnupg/S.gpg-agent:$(pgrep gpg-agent):1"
eval `keychain --noask --eval --agents gpg,ssh --inherit any --timeout $LIFE id_rsa`
export GPG_TTY=`tty`
```

**Comment by x48rph** [comment]
This issue was fix awhile ago
