### ISSUE TITLE
keychain does not load pem keys

### ISSUE THREAD

**Issue by eedgar** [funtoo/keychain#64]
I am trying to load a key like this

`keychain ~/.ssh/build.pem`

`* Warning: Cannot find public key for ~/.ssh/build.pem`

using ssh-add works fine.
`ssh-add ~/.ssh/build.pem`
`Identity added: ~.ssh/build.pem
` (~/.ssh/build.pem)`

**Comment by ensonik** [comment]
Same here. Can't manage my Mesosphere and AWS keys because of this.

**Comment by tjaartvdwalt** [comment]
Hi, I just had the same issue. I wanted to add my AWS EC2 pem to keychain.

Sure enough, when I looked into my `.pem` file, it had only a private key, so I tried the following experiment.

To obtain my public key I logged into my EC2 instance, and copied the public key from `~/.ssh/authorized_keys`. I copied it into a file named similar to the `.pem`, but with a `.pub` extension. So now I had 2 files:

```
my-key.pem
my-key.pub
```
then I was able to import the key:
```
keychain my-key.pem
```
and after that I was able to ssh into my server without specifying the the keyfile.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/<tornado.concurrent.Future object at 0x7f806deacfd0>

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/<tornado.concurrent.Future object at 0x7f27e6edec50>

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3409

**Comment by x48rph** [comment]
A fix for this has been added to the devel branch and will appear in a future version. When using a 'pem' key you will be required to enter your passphase twice, once to get the public key fingerprint and again when the key is actually added. This can be avoided by adding a separate '.pub' file containing the public key.
