### ISSUE TITLE
gpg key passphrase not cached 

### ISSUE THREAD

**Issue by Konfekt** [funtoo/keychain#65]
Under OpenSUSE 42.1, gpg 2.1.15 and keychain 2.8.3 (current master), after `eval "$(keychain --agents gpg ---eval 99999999)"` (some key) and entering the correct passphrase in the pinentry-program, the entered passphrase does not persist in cache. 

Instead, the pinentry-program asks again for the passphrase the next time needed. (For example, `eval "$(keychain --agents gpg ---eval 99999999)"` will also ask for the passphrase again.)

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/<tornado.concurrent.Future object at 0x7f806de61860>

**Comment by Konfekt** [comment]
Ok. How to contact the JIRA admins to create an account?

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3412

**Comment by danielrobbins** [comment]
http://auth.funtoo.org:9093/new can be used to create a Funtoo account.

**Comment by x48rph** [comment]
I tested this and can not reproduce this behavior if I try using the key within the given cache time. This appears to be the same issue as https://github.com/funtoo/keychain/issues/91 where the key only remains in the cache for a short period of time by default. I've updated the documentation at https://www.funtoo.org/Keychain to inform users of this. If you still experience this issue with the latest version , 2.8.4 , and you are using the key within the specified cache time then please open a new issue and I will investigate further. Thanks.

**Comment by Konfekt** [comment]
This issue is probably due to `$GNUPGHOME` being set, which causes `$SSH_AUTH_SOCK` to contain a random string such as `/run/user/1000/gnupg/d.i...z/S.gpg-agent.ssh` instead of  simply `/run/user/1000/gnupg/S.gpg-agent.ssh`.
