### ISSUE TITLE
add to the doc: ForwardAgent yes

### ISSUE THREAD

**Issue by Sispheor** [funtoo/keychain#68]
Do not forget to add `ForwardAgent yes` in _/etc/ssh/ssh_config_

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/<tornado.concurrent.Future object at 0x7f806de9a940>

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/<tornado.concurrent.Future object at 0x7f27e6e91748>

**Comment by x48rph** [comment]
While users may or may not wish to use ssh agent fowarding , it's not necessary for keychain to work and therefore outside it's scope
