### ISSUE TITLE
Fish shell problem

### ISSUE THREAD

**Issue by dehein** [funtoo/keychain#72]
When i try to use the fish shell, i enter the needed snippet in my fish config, but i get these errors:
`Unsupported use of '='. In fish, please use 'set SSH_AUTH_SOCK /tmp/ssh-xnA5AcVFHhKY/agent.1204'.
- (line 1): SSH_AUTH_SOCK=/tmp/ssh-xnA5AcVFHhKY/agent.1204; export SSH_AUTH_SOCK;
            ^
from sourcing file -
	called on line 67 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

Unsupported use of '='. In fish, please use 'set SSH_AGENT_PID 1206'.
- (line 2): SSH_AGENT_PID=1206; export SSH_AGENT_PID;
            ^
from sourcing file -
	called on line 67 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

`

And even if i just use this command, instead of the recommended 
`# keychain alternative ??
if status --is-interactive;
    keychain ~/.ssh/id_rsa
end`

i get the problem, that i can't really can't use my ssh keys.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3495

**Comment by x48rph** [comment]
I tested keychain with fish shell and in my opinion, this is a problem for the fish shell developers and not an issue with keychain. Not sure why 'sourcing' was ever recommended as it obviously fails since fish shell os not POSIX compliant. Prehaps in the past ot worked but no longer does. Also, just executing keychain in the
