### ISSUE TITLE
bash conditionals

### ISSUE THREAD

**Issue by latkinson** [funtoo/keychain#77]
Tested on Ubuntu Xenial.

When reading .ssh/config, keychain uses the "[[" bash builtin. However, the shebang is running the script as "/bin/sh". Calling it through "bash keychain ..." works for me, but I just wondered if "[[" should work and something else is wrong?

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3688

**Comment by x48rph** [comment]
This is fixed in the latest version 2.8.3
