### ISSUE TITLE
Unterminated quoted string error

### ISSUE THREAD

**Issue by fortes** [funtoo/keychain#78]
I get the following when running on debian stable and bash 4.4.11:

```
localhost:~ uname -a
Linux localhost 3.14.0 #1 SMP PREEMPT Wed Apr 5 13:09:13 PDT 2017 x86_64 GNU/Linux
localhost:~ keychain

 * keychain 2.8.2 ~ http://www.funtoo.org
/usr/bin/keychain: 2: eval: Syntax error: Unterminated quoted string
```

This is a fairly recent error, probably in the last week? Haven't changed anything in my config, I usually call the following in my `.profile` (also gives the same error):

`eval "$(keychain --eval --noask --agents ssh --quiet)"`

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3727

**Comment by x48rph** [comment]
I've tried a bunch of times an I can not reproduce this error. Please upgrade to the current 2.8.3 and if you still have this problem, open a new issue.  Thanks.

**Comment by fortes** [comment]
No longer reproduces on bash 4.4.12
