### ISSUE TITLE
Truncated example for fish shell

### ISSUE THREAD

**Issue by jruere** [funtoo/keychain#79]
In http://www.funtoo.org/Keychain, the first fish example is truncated. I suppose it should be:

```
if status --is-interactive
  keychain --eval --quiet -Q id_rsa | source
end
```

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-3955

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
